-- the following tables define what questions the officer ("OFC") will ask / what orders the officer will give / what information the officer conveys.
-- the answers of the ped ("Normal") are defined as well.
NormalAddress = {'Hello Officer.', 'How can I help you?'}
NormalGreetResponse = NormalAddress
NormalLicenceResponse = {'Sure, here it is.', 'Of course, officer.'}
NormalLicenceHideResponse = {"Uh, I can't find it right now...", "Hmm... it must be here somewhere.", "Sorry officer, I seem to have lost it."}
NormalNoLicenceResponse = {"I don't possess one, Officer.", "I don't have one, sorry."}
NormalNoDrugResponse = {"No, I don't do drugs.", "No, Officer, that would be illegal.", "Of course not."}
NormalDrugResponse = {"D.D.Drugs? N.n.no.", "So many colors."}
NormalNoAlcoholResponse = {"No, I didn't drink anything.", "No, Officer."}
NormalAlcoholHideResponse = NormalNoAlcoholResponse
NormalAlcoholResponse = {"Yeah, I drank a bit, but it's not much.", "I might have taken a couple shots, you know...", "Yeah, but that's not illegal, Officer."}
NormalNoIllegalItemsResponse = {"No, Officer.", "Of course not.", "I don't possess anything illegal."}
NormalIllegalItemsResponse = {"Well, actually I found this a few minutes ago...", "Illegal items? Nooo..."}
NormalIllegalItemsHideResponse = NormalNoIllegalItemsResponse
NormalNoWeaponsResponse = {"I'm unarmed.", "No, Officer.", "I don't possess any weapon."}
NormalWeaponsResponse = {"Yes, I carry a weapon with me.", "I'm armed.", "Yes, Officer.", "Yes, I found this weapon...", "Yes, but that's perfectly fine."}
NormalWeaponsHideResponse = NormalNoWeaponsResponse
NormalIllegalWeaponsResponse = NormalWeaponsResponse
NormalIllegalWeaponsHideResponse = NormalNoWeaponsResponse
NormalAnswerStartingPoint = {"I started at home.", "I'm coming from work.", "Coming from the strip club.", "Just exited the bank.", "Was shopping some groceries.", "Nowhere in particular.", "Coming from the prison.", "Coming from the police station.", "I was at home."}
NormalAnswerDestination = {"I'm going home.", "On my way to work.", "Going to get some pizza.", "Nothing special.", "I'm going to the strip club to look at your mom.", "I need to buy some groceries.", "I'm going to the bank.", "I'm going to the police station."}
NormalAnswerActivity = {"I'm walking here!", "I'm just walking.", "Standing around, doing nothing.", "Just wandering around aimlessly.", "To be honest, I don't really know..."}
NormalAnswerNoSuspiciousActivity = {"I didn't see nothing.", "No, Officer, nothing suspicious.", "Nothing out of the ordinary."}
NormalNoVehicleResponse = {"Officer, there's no vehicle.", "Officer, I don't own a vehicle.", "What vehicle?", "Officer, are you insane? There is no vehicle..."}
NormalAcceptOrderResponse = {"Yes, Officer.", "Ok, Officer.", "I understand.", "Go ahead."}
NormalRefuseOrderResponse = {"No, Officer.", "No.", "This won't happen, Officer.", "I object."}
NormalRefuseQuestionResponse = {"You don't need to know this.", "There is no reason for you to get that information.", "Officer, I refuse to answer.", "I refuse to answer.", "I won't give you that information."}
NormalResistActionResponse = {"Don't touch me!", "You can't do this!", "Stop touching me!", "Step back!"}
NormalStopInteractionResponse = {"Officer, I'll not continue talking to you. Bye."}
NormalFleeResponse = {"Don't follow me, Officer!"}
NormalFightResponse = {"You will pay for this!"}
NormalWaitResponse = {'Please hurry up.', "Ok, I'll wait.", 'Ok, Officer.'}
NormalGoodbye = {'See you soon.', 'Bye.', 'Goodbye.', 'Good day, Officer.', 'Have a good day.'}

OFCAskForID = {'May I see your ID please?', 'Give me your ID.', 'ID please.', 'Do you have identification on you?'}
OFCAskForDriverLicence = {"May I see your driver's licence please?", "Driver's licence please.", "Give me your driver's licence.", "Do you have a driver's licence?"}
OFCAskForGunLicence = {"May I see your weapon permit please?", "Give me your weapon permit.", "Weapon permit please.", "Do you have a weapon permit?"}
OFCAskForSubstance = {"Did you take any controlled substances?", "Are you doing drugs?"}
OFCAskForAlcohol = {"Have you been drinking?", "Did you drink alcohol today?", "Are you drunk?"}
OFCAskForIllegalItems = {"Do you have anything illegal with you?", "Are you carrying something you shouldn't?"}
OFCAskForWeapons = {"Are you carrying a firearm?", "Are you armed?", "Do you carry weapons?"}
OFCAskForStartingPoint = {"Where did you go on road?"}
OFCAskForDestination = {"What's your destination?"}
OFCAskForActivity = {"What are you doing currently?"}
OFCAskForSuspiciousActivity = {"Did you notice anything suspicious lately?"}
OFCOrderOutOfVehicle = {"Please exit the vehicle.", "Exit the vehicle immediately!", "Get out of the vehicle."}
OFCOrderIntoVehicle = {"Please enter the vehicle.", "Get into the vehicle immediately!", "Get back into the vehicle."}
OFCInformBreathalyzer = {"Please use the breathalyzer.", "I'd like to test your alcohol level.", "Please blow into the breathalyzer."}
OFCInformDrugtest = {"Please use the drug tester.", "I'd like to test you on illegal substances."}
OFCInformPersonSearch = {"Please submit to a search of yourself.", "I'd like to search you. Is there anything in the pockets that can hurt me?", "You are going to get searched."}
OFCInformCarSearch = {"I'll search your car.", "Please open the car to be searched."}
OFCInformCarSeizure = {"I have to seize your car.", "You are not allowed to drive this car anymore.", "You car will be confiscated."}
OFCInformObjectConfiscation = {"I need to take these objects off of you.", "I'll confiscate these objects from you."}
OFCInformArrest = {"You are under arrest.", "Please turn around, you are arrested."}
OFCInformFine = {"That's gonna be a ticket.", "I need to issue you a ticket."}

OFCWait = {"Please wait here, I'll come back to you.", "Please wait here.", "Please remain in the area, so I can check back on you."}
OFCBye = {'Have a good day.', 'Alright, you can go.', 'Goodbye.', 'Get lost.', 'See you.'}